# Numpy Tutorial

In [1]:
#numpy math modules
import numpy as np
m1=np.array([5,21,7])
print(m1)

[ 5 21  7]


In [2]:
m2=np.array([(1,2,3),(4,5,6)])
print (m2)

[[1 2 3]
 [4 5 6]]


In [5]:
m1[0]


5

In [6]:
m2[1,2]

6

# zeros method

In [8]:
m3=np.zeros(3)
print(m3)

[0. 0. 0.]


In [41]:
m4=np.zeros((3,3),dtype=int)
print(m4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
m5=np.zeros((2,3,4))
print(m5)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# ones method

In [12]:
m6=np.ones(3)
print(m6)

[1. 1. 1.]


In [13]:
m7=np.ones((3,3))
print(m7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
m8=np.ones((2,3,4))
print(m8)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# full method

In [15]:
m9=np.full((3,3),5)
print(m9)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


# eyes method

In [16]:
m10=np.eye((3))
print(m10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# create 4x4 in diagonal 5

In [24]:
m11=np.zeros((4,4),int)
np.fill_diagonal(m11,5)
print(m11)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


In [23]:
m12 = np.eye((4))
print(m12)
for i in range(4):
    for j in range(4):
        if m12[i][j] == 1.0:
            m12[i][j]=5.0
print(m12)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


# add and subtract of two matrix from user input

In [25]:
r=int(input("enter row:"))
c=int(input("enter column:"))
m1=np.zeros((r,c))
m2=np.zeros((r,c))
print("matrix1")
for i in range (r):
    for j in range (c):
        v=int(input("enter values:"))
        m1[i,j]=v
print("matrix2")
for i in range (r):
    for j in range (c):
        v=int(input("enter values:"))
        m2[i,j]=v
print(m1)
print(m2)
#addition of two matrices
print(m1+m2)
#subtraction of two matrices
print(m1-m2)

enter row:3
enter column:3
matrix1
enter values:1
enter values:2
enter values:3
enter values:4
enter values:5
enter values:6
enter values:7
enter values:8
enter values:9
matrix2
enter values:1
enter values:2
enter values:3
enter values:4
enter values:5
enter values:6
enter values:7
enter values:8
enter values:9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# operations

In [27]:
#sort
m13=np.array([(6,3,7),(9,5,8)])
m13.sort()
print (m13)

[[3 6 7]
 [5 8 9]]


In [80]:
#reshape() learn
m14 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
m141 = m14.reshape(2, 3, 2)
print(m141)

m14 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
m141 = m14.reshape(3, 3)
print(m141)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
#append
m15=np.array([1,3,6])
m15=np.append(m15,5)
print(m15)
m15=np.append(m15,7)
print(m15)

[1 3 6 5]
[1 3 6 5 7]


In [46]:
#insert
m16=np.array([1,3,6])
m16=np.insert(m16,2,9)
print(m16)

[1 3 9 6]


In [49]:
#delete
m17=np.array([1,2,3,4,5,6,7,8,9])
m17=np.delete(m17,2,axis=0)
print(m17)

[1 2 4 5 6 7 8 9]


In [82]:
#split
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [61]:
#random
m20=np.random.rand(3,3)
print(m20)

[[0.55130189 0.36585478 0.87878862]
 [0.96644059 0.48028255 0.02236025]
 [0.06407628 0.16067688 0.12230022]]


In [65]:
m21=np.array([1,2,3,4,5,6,7,8,9])
print(m21[0:2])
print(m21[2:])
print(m21[:3])

[1 2]
[3 4 5 6 7 8 9]
[1 2 3]


In [84]:
rmat=np.random.rand(5,5)
print(rmat)
print(rmat[0:3,4])
print(rmat[:,4])
print(rmat[[3],:3])
print(rmat[1:3,2])

[[0.21421592 0.99512004 0.61712677 0.29529513 0.22808171]
 [0.84346232 0.50647448 0.03662679 0.76262934 0.82143113]
 [0.77749108 0.81284129 0.20204646 0.40907921 0.58349556]
 [0.01218201 0.66534427 0.88939818 0.79341778 0.95655777]
 [0.90989475 0.18345612 0.28562036 0.27225467 0.43227738]]
[0.22808171 0.82143113 0.58349556]
[0.22808171 0.82143113 0.58349556 0.95655777 0.43227738]
[[0.01218201 0.66534427 0.88939818]]
[0.03662679 0.20204646]


In [76]:
#aggregate function( sum, mean, median, max , min )
m22=np.array([1,4,77,3,2,44])
print(m22.sum())
print(m22.min())
print(m22.max())
print(m22.mean())

131
1
77
21.833333333333332


In [77]:
demo=np.random.rand(10,5)
print(demo)

[[0.51349537 0.2477947  0.86240824 0.1215741  0.56612966]
 [0.07702434 0.92258689 0.49611127 0.55598367 0.32944176]
 [0.09466702 0.87204917 0.07151956 0.62634591 0.29211937]
 [0.26621993 0.20826764 0.01881393 0.78054938 0.87142616]
 [0.60514335 0.10604477 0.25667806 0.64230467 0.87109609]
 [0.80111778 0.97937359 0.1289729  0.52286852 0.57246353]
 [0.58025418 0.76863855 0.80999834 0.39537468 0.98293569]
 [0.73044475 0.53602407 0.76266896 0.12779568 0.96361713]
 [0.99530877 0.33001787 0.23934561 0.28159223 0.6825303 ]
 [0.80165381 0.35043029 0.08248615 0.94078974 0.79081518]]


In [78]:
print(demo.max())

0.9953087677197461


In [88]:
import cv2
import numpy as np

img = cv2.imread('home.jpg')
res = cv2.resize(img, dsize=(54, 140), interpolation=cv2.INTER_CUBIC)

In [90]:
#get image and resize to (600x600)
from PIL import Image
#Open image using Image module
im = Image.open("home.jpg")
#Show actual Image
im.show()
#Show rotated Image
im = im.resize((600,600))
im.show()